#!/usr/bin/env python
import glob
import mincemeat
import operator




text_files = glob.glob('hw3data\*')
def file_contents(file_name):
    f = open(file_name)
    try:
        return f.read()
    finally:
        f.close()

source = dict((file_name,file_contents(file_name)) for file_name in text_files)

def mapfn(key,value):
    import stopwords
    print key,value
    for line in value.splitlines():
        segments = line.split(":::")
        authors = segments[1].split("::")
        words = str(segments[2]).split(" ")
            
        for author in authors:
            for word in words:
                if word not in stopwords.allStopWords.keys():
                    yield author,word
                    
def reducefn(key, value):
    #key - string
    #value - listj
    from collections import Counter
    return Counter(value)                    


#def mapfn(key, value):
#    for line in value.splitlines():
#       for word in line.split():
#           yield word.lower(),1
 
#def reducefn(key, value):
#    return (key, len(value))


s = mincemeat.Server()
s.datasource = source
s.mapfn = mapfn
s.reducefn = reducefn

results = s.run_server(password = "changeme")

resultline = str(results).split("),")
f = open('outfile.txt','w')
for result in resultline:
    f.write(str(result)+'),\n')
f.close()

                
